### ISSUE TITLE
I want to run this extension in front of other tasks. How can I get the driver binary path?

### ISSUE THREAD

**Issue by SchlauFuchs** [erdi/webdriver-binaries-gradle-plugin#14]
Don't ask me why, but I need the Webdriver executable system property set within a Spring Boot bootRun task execution. How can I do this?

**Comment by erdi** [comment]
You should not do that @thokari because as you've mentioned it's done during configuration phase. This means that it will happen during every build invocation even if the driver executable is not needed for that particular invocation which will unnecessary slow the build down.

I'm close to finishing with #9 (I only need to update the docs), I will then tackle this and I'm hoping to do a release either this week or the next. So hopefully soon one will not need to resort to either verbose code or hacks.
