### ISSUE TITLE
detect the browser version automatically 

### ISSUE THREAD

**Issue by rameshnatesan** [erdi/webdriver-binaries-gradle-plugin#26]
hi,
Can you please add a feature to detect the browser version automatically and then pick the appropriate driver?
Right now, we have to specify the version ourselves. 

Thanks

**Comment by erdi** [comment]
Doing this across multiple OSes and browsers currently supported by the plugin is a significant amount of work an it's non-trivial. Also, a mapping from browser version to driver version would need to be somehow provided and maintained because they don't map one to one. 

I personally don't have a need for such functionality and do not have capacity to work on it but you're more than welcome to submit a PR.
